### ISSUE TITLE
Animations that are fully crossfaded out (targetWeight == 0) are still 'playing' internally in the background

### ISSUE THREAD

**Issue by Zhang941** [Unity-Technologies/SimpleAnimation#13]
Repro:
Crossfade Animation A into Animation B.
Play Animation A at random intervals. Animation A will not start at clip time 0, instead it will play at whatever clip time the animation is currently looped at.

Not sure if this is a bug or by design. It is a bug for all the scenarios I'm using crossfade for.
Here's a rough fix suggestion:

```
SimpleAnimationPlayable.cs

private void UpdateStates(float deltaTime)
    {
       .....
line 533:
                if (state.weight == state.targetWeight)
                {
                    state.fadeSpeed = 0f;
                    state.fading = false;

                    ++if (state.targetWeight == 0)
                    ++{
                    ++    DisableState(state, i);
                    ++}
                }
                state.weightDirty = true;
            }
     .....


    private void DisableState(StateInfo state, int i)
    {
        state.weight = 0f;
        state.time = 0f;
        state.playable.SetTime(state.time);
        state.playable.SetTime(state.time);
        m_States.DisableState(i);
        if (!keepStoppedPlayablesConnected)
            DisconnectInput(state.index);
        state.weightDirty = true;
    }

```

**Comment by ifayad** [comment]
Nice Catch. Your suggestion should fix it. I don't think the component has been thoroughly tested, maybe they didn't have enough time (or issues have been overlooked) since all the issues can be fixed easily or implemented (I am looking at you set state WrapMode not implemented).

**Comment by davidg-unity** [comment]
Thanks for reporting this. The pull request just above should fix the issue.
> I don't think the component has been thoroughly tested,

Being outside the official Unity release process, this project doesn't have full manual QA coverage.  The automated tests included in the project _should_ have covered all possible cases, but there's nothing like actual people making actual content with it to find out what you missed in your test cases.

Built-in components go through the official Unity Beta, and get some eyes on them before official release, and we get a chance to iron out the bugs.

For open source repositories like this, the only way for us to get people to try it with actual use cases, is to publish it and get feedback. 

>I am looking at you set state WrapMode not implemented
Right... I should have covered this in the Wiki, and left a more meaningful comment.

@ifayad if you open a separate issue for this one I can give you a more in-depth explanation, but the short version is: the engine-side implementation of AnimationClipPlayable doesn't play nice with WrapMode, mainly because it's supposed to be a Legacy-only option. Until we (the Animation Team) address this in the Unity Code, implementing this in C# is probably possible, but it would end up way messier than it should be.

**Comment by davidg-unity** [comment]
Fixed in https://github.com/Unity-Technologies/SimpleAnimation/pull/11 
Merged to master
