### ISSUE TITLE
Playing more than 1 Queued animation causes infinite loop

### ISSUE THREAD

**Issue by drew-fitcraft** [Unity-Technologies/SimpleAnimation#45]
hi,

I want to play 3 animations in sequence, one after the other, only after the first one finishes. I am using the PlayQueued() or CrossFadeQueued() for this with "QueueMode.CompleteOthers" setting.

I found that if I called PlayQueued() while there already is still one animation in the Queue, what happens is a very weird infinite loop of animations. Basically, after all animations play once, these animations stay in the queue and just repeat over and over, playing for about 1 second each.

What is happening and how can I prevent this?

**Comment by SilentSin** [comment]
I don't actually use Simple Animation because my Animancer plugin is much better (it's on the asset store). But I have done various comparisons against Simple Animation including queueing and haven't run into anything like that. I don't specifically remember queueing multiple animations at once though. Have you tried debugging your way through the code?

Also, I think you could have just put @SilentSin in this thread instead of posting in an unrelated issue to get me notified.

**Comment by drew-fitcraft** [comment]
Thanks @SilentSin, I created the issue because it seems like a legit bug. The SimpleAnimation never removes the animation from the queue after it's done. I fixed it by removing the entry from the queue when it completes.

BtW - thank you so much for sharing Animancer. I havent heard of it and it seems exactly what I'm looking for. I didn't see Queuing in your docs, but looks like I can replicate that by using the callbacks and playing the next animation after one ends? That is amazing. Will play with it tommorow.. sounds like it could he perfect!

**Comment by SilentSin** [comment]
Yeah that's exactly right. I never liked the idea of using the animation system as a state machine beyond the simple "play this and tell me when you're done", so I went for an event based approach instead of queuing. It's still just as easy to say "play 'attack' then 'idle'", but there's no reason why you should need to declare the idle up front. Maybe you want to choose between idle and another attack depending on whether the player pressed the button again, or do a backstab if you're behind an enemy. Or maybe you don't even want to play another animation yet, you just want to know that the jump animation is finished so you can start checking if you're going down to start the falling animation. This way gives much more flexibility. Feel free to contact me via the email address listed on the store page and in the user manual if you have any questions or feedback.

Also, you didn't need to put @SilentSin there because it would have notified my of any new posts anyway after I had already posted in this thread.
