### ISSUE TITLE
CrossFade() doesn't work as expected

### ISSUE THREAD

**Issue by ratkingsminion** [Unity-Technologies/SimpleAnimation#9]
Using it like myAnim.CrossFade("Walk", 0.2f) does not fade the current animation to the walking animation within 0.2 seconds. I am not sure what it actually does.

**Comment by ifayad** [comment]
That's weird. It's working fine on my end. Did you make sure CrossFade is not called over and over again ?

**Comment by ratkingsminion** [comment]
Well, I actually call it every frame - because this is possible with the legacy animation system without problems. So this is either a real issue or at least a documentation issue.

**Comment by ifayad** [comment]
I faced the same issue, that's why I thought you are also calling it every frame. However, I did not give it much thought because I never worked with the legacy animation system and assumed that's how it should behave. However, since you mentioned it, I retraced the code and found what I think is the issue. The current implementation is using the same function (SetupLerp) to set the weights for both the cross fading and the blending functions. This function subtracts the target weight from the clip to cross-fade-to or blend-with (originally set at 0) with the target weight (set at 1 for cross fade), if the absolute value of this subtraction is higher than zero, the clip is set to be faded at a later stage. Then the target weight is assigned to the target weight field in the clip. Basically like this:
```

        float travel = Mathf.Abs(state.targetWeight - targetWeight);

        state.fading = travel > 0f;

        state.fadeSpeed = time != 0f ? travel / time : Mathf.Infinity;
        state.targetWeight = targetWeight;
```

originally state.targetWeight is 0, at the end of the code it is set to targetWeight, and this is the issue. When first calling the cross fade function, state.targetWeight is different than targetWeight, however, when calling it again before it has finished fading, both values are equal, and the clip is set to not fade. To fix it, just replace state.targetWeight in the first line with state.weight (which makes more sense to me): if current weight different than target weight you can fade. you can find the SetupLerp in SimpleAnimationPlayable.cs. I did a quick test and it worked, but no guarantees of other issues it may cause.

**Comment by davidg-unity** [comment]
@ratkingsminion 
Thanks for reporting this.
I have taken a look at the AnimationComponent code, and its States indeed discard any new Crossfade time to the same weight if the resulting Crossfade is slower than the previous one.

I have aligned the SimpleAnimation code to behave the same way, and added a test to cover this case.
The Pull Request for the changes is [here](https://github.com/Unity-Technologies/SimpleAnimation/pull/11)

Could you please validate that this indeed fixes your issue?

**Comment by ifayad** [comment]
Thanks David. the changes seem to fix the issue. Just a simple note, the end of the comment in SetupLerp: 
"// If we're fading to the same target as before but faster"

instead of faster it should be slower I think.

**Comment by davidg-unity** [comment]
>instead of faster it should be slower I think.
Yes, you're correct. I had the logic written the other way around and forgot to clean up the comment after changing it.

**Comment by ratkingsminion** [comment]
Thanks, it works now.
